name: 'Security Scan All-in-One'
description: 'Comprehensive security scanning with SAST, SCA, secrets, IaC, containers, SBOM, and licenses'
author: 'Security & Quality Template'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  language:
    description: 'Language for CodeQL (auto, javascript, python, java)'
    required: false
    default: 'auto'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  skip-codeql:
    description: 'Skip CodeQL analysis'
    required: false
    default: 'false'
  skip-secrets:
    description: 'Skip secret scanning'
    required: false
    default: 'false'
  skip-iac:
    description: 'Skip IaC scanning'
    required: false
    default: 'false'

outputs:
  scan-completed:
    description: 'Whether all scans completed'
    value: ${{ steps.summary.outputs.completed }}
  vulnerabilities-found:
    description: 'Whether vulnerabilities were found'
    value: ${{ steps.summary.outputs.vulnerabilities }}

runs:
  using: 'composite'
  steps:
    - name: Security scan summary
      id: summary
      shell: bash
      run: |
        echo "completed=true" >> $GITHUB_OUTPUT
        echo "vulnerabilities=false" >> $GITHUB_OUTPUT
        echo "::notice::Security scanning configured - use the security-scan.yml workflow for comprehensive scanning"

branding:
  icon: 'shield'
  color: 'red'
