name: 'Language Detection'
description: 'Automatically detect project language (Node.js, Python, Java)'
author: 'Security & Quality Template'

inputs:
  override-language:
    description: 'Override auto-detection with specific language'
    required: false
    default: 'auto'

outputs:
  detected-language:
    description: 'Primary detected language'
    value: ${{ steps.detect.outputs.language }}
  has-nodejs:
    description: 'Whether Node.js project files are present'
    value: ${{ steps.detect.outputs.has-nodejs }}
  has-python:
    description: 'Whether Python project files are present'
    value: ${{ steps.detect.outputs.has-python }}
  has-java:
    description: 'Whether Java project files are present'
    value: ${{ steps.detect.outputs.has-java }}

runs:
  using: 'composite'
  steps:
    - name: Detect project language
      id: detect
      shell: bash
      run: |
        OVERRIDE="${{ inputs.override-language }}"
        DETECTED_LANG="unknown"
        HAS_NODEJS="false"
        HAS_PYTHON="false"
        HAS_JAVA="false"

        # Check for Node.js indicators
        if [ -f "package.json" ] || [ -f "package-lock.json" ] || [ -f "yarn.lock" ] || [ -f "pnpm-lock.yaml" ] || [ -f "bun.lockb" ]; then
          HAS_NODEJS="true"
          DETECTED_LANG="nodejs"
          echo "✓ Node.js project detected"
        fi

        # Check for Python indicators
        if [ -f "requirements.txt" ] || [ -f "setup.py" ] || [ -f "pyproject.toml" ] || [ -f "Pipfile" ] || [ -f "poetry.lock" ]; then
          HAS_PYTHON="true"
          if [ "$DETECTED_LANG" = "unknown" ]; then
            DETECTED_LANG="python"
            echo "✓ Python project detected"
          fi
        fi

        # Check for Java indicators
        if [ -f "pom.xml" ] || [ -f "build.gradle" ] || [ -f "build.gradle.kts" ] || [ -f "gradlew" ] || [ -f "mvnw" ]; then
          HAS_JAVA="true"
          if [ "$DETECTED_LANG" = "unknown" ]; then
            DETECTED_LANG="java"
            echo "✓ Java project detected"
          fi
        fi

        # Check for additional languages
        if [ -f "go.mod" ] || [ -f "go.sum" ]; then
          echo "ℹ Go project detected (partial support)"
        fi

        if [ -f "Cargo.toml" ]; then
          echo "ℹ Rust project detected (partial support)"
        fi

        if [ -f "composer.json" ]; then
          echo "ℹ PHP project detected (partial support)"
        fi

        # Apply override if specified
        if [ "$OVERRIDE" != "auto" ] && [ "$OVERRIDE" != "" ]; then
          DETECTED_LANG="$OVERRIDE"
          echo "⚠ Language overridden to: $OVERRIDE"
        fi

        echo "language=$DETECTED_LANG" >> $GITHUB_OUTPUT
        echo "has-nodejs=$HAS_NODEJS" >> $GITHUB_OUTPUT
        echo "has-python=$HAS_PYTHON" >> $GITHUB_OUTPUT
        echo "has-java=$HAS_JAVA" >> $GITHUB_OUTPUT

        echo "::notice::Detected language: $DETECTED_LANG (Node.js: $HAS_NODEJS, Python: $HAS_PYTHON, Java: $HAS_JAVA)"

branding:
  icon: 'search'
  color: 'blue'
